spring:
  datasource:
    url: jdbc:mysql://119.29.183.231:3306/wordpress?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: hong1314
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: dfskfsfsd
  expireMinutes:
    authToken: 300
    refreshToken: 360

    
file:
  storage:
    root:
      dir: /data/fileStorage/libra/
    tmp:
      dir: /data/fileStorage/temp/libra/
    prefix: /attachment/