spring:
  datasource:
    url: jdbc:mysql://119.29.183.231:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: hong1314
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.graduation.blog.domain

mapper:
 mappers: com.graduation.blog.base.MyMapper
 identity: mysql


jwt:
  secret: dfskfsfsd
  expireMinutes:
    authToken: 300
    refreshToken: 360

    
file:
  storage:
    root:
      dir: C:/data/fileStorage/blog/
    tmp:
      dir: /data/fileStorage/temp/blog/
    prefix: /attachment/
    document:
      dir: /data/document/
      pdfUrl: http://localhost:8080